### ISSUE TITLE
Import into Ghidra 9.2.2 not possible

### ISSUE THREAD

**Issue by yetipenguin** [ubfx/BinDiffHelper#10]
When trying to import ghidra_9.2_BinDiffHelper_0.3.2.zip into ghidra_9.2.2_PUBLIC_20201229 it says that the plugin is not compatible with the Ghidra version.

Workaround:
Unzip the ghidra_9.2_BinDiffHelper_0.3.2.zip and edit extensions.properties.
Change
"version=9.2"
to
"version=9.2.2"
then import the plugin directly from the unzipped folder.

**Comment by ubfx** [comment]
Thanks for the report, and sorry for my long response time. I will update the binary releases and report back

**Comment by ubfx** [comment]
I added a build for Ghidra 9.2.2 to the release page.

https://github.com/ubfx/BinDiffHelper/releases/tag/v0.3.2

If you're still working with the software it would be nice if you could give me a quick feedback if it now works as intended.

**Comment by yetipenguin** [comment]
Thank you very much for the new version! :-) It can be imported into Ghidra 9.2.2.
