### ISSUE TITLE
Support for Bindiff 7, Ghidra 10

### ISSUE THREAD

**Issue by deefdragon** [ubfx/BinDiffHelper#11]
Can you push a release for Bindiff7/Ghidra 10? It also looks like Bindiff7 now has exporter by default, so that should simplify things.

**Comment by ubfx** [comment]
I haven't tried the new bindiff yet but I will look into it and try to incorporate it. Ghidra 10 shouldn't be a problem.

**Comment by the-entire-country-of-ireland** [comment]
Simply changing all the `.startsWith("BinDiff 6")` checks to `.startsWith("BinDiff 7")` has it work perfectly

**Comment by astewart43-gtri** [comment]
@ubfx Would it be possible to make a release that incorporates the above? Compatibility with Ghidra 10 and BinDiff 7 would be super helpful for my application.

**Comment by ubfx** [comment]
Hallo everyone. Sorry for the delay.

@astewart43-gtri 
Can you try this release: https://github.com/ubfx/BinDiffHelper/releases/tag/v0.4.0
I hope it should work like this.
