### ISSUE TITLE
Provide binary for Ghidra 10.1.x

### ISSUE THREAD

**Issue by bvernoux** [ubfx/BinDiffHelper#12]
Could you provide a binary (pre-built plugin) for latest Ghidra 10.1.1 (https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1.1_build) ?

**Comment by tekwizz123** [comment]
Now 10.1.4, in either case I think 10.1.x introduced changes that this program is not compatible with, would be nice to get an update for this as I can't seem to compile this program for those versions.

**Comment by throwaway-a** [comment]
3rd-ed. Current build won't work with 10.1.x. Also just noticed that if I want to downgrade to 10.0.x to get the previous binary working, I'd have to accept running a version with the Log4J vulnerability!

**Comment by ubfx** [comment]
Sorry for the late update. Here are binaries for 10.1.3 and 10.1.4, let me know if there are any more problems with those:
https://github.com/ubfx/BinDiffHelper/releases/tag/v0.4.1

**Comment by throwaway-a** [comment]
I tried with 10.1.4 on Windows. The plugin shows up fine under "Install Extensions", including after I restart Ghidra.

![image](https://user-images.githubusercontent.com/77025740/181362254-23dd1bc7-1c67-4564-b21c-9a059dca1b23.png)

However, when I go to Configure -> Configure All, I don't see it:

![image](https://user-images.githubusercontent.com/77025740/181362405-d0ae6c29-d7b6-4666-9880-4b4ec1e142fa.png)

(Also I just want to confirm, "BinDiff" is listed under "Recommended other tools" so it's not 100% required to do baseline diffing within Ghidra, correct? (Is BinDiff functionality therefore built in at this point? I think I had saw an announcement about that, but wasn't sure if I was interpreting it correctly.))

**Comment by ubfx** [comment]
> However, when I go to Configure -> Configure All, I don't see it:

That's normal. The plugin is configured within the CodeBrowser (just open any binary in the CodeBrowser and in the Menu under "Window", there should be an item BinDiffHelper



> Also I just want to confirm, "BinDiff" is listed under "Recommended other tools" so it's not 100% required to do baseline diffing within Ghidra, correct? (Is BinDiff functionality therefore built in at this point

It's not strictly required because theoretically, you could diff on another machine and just use the output files of BinDiff with the plugin. The diffing functionality itself will never be able to be integrated because BinDiff is a proprietary tool. So for everything to work best you should use the BinExport plugin and have BinDiff installed.

**Comment by throwaway-a** [comment]
> That's normal. The plugin is configured within the CodeBrowser (just open any binary in the CodeBrowser and in the Menu under "Window", there should be an item BinDiffHelper

OK, maybe the Usage section of the Readme.md can be removed at this point then?

**Comment by ubfx** [comment]
Sorry, I misunderstood. The Usage section is still correct in that the Plugin needs to be checked in the CodeBrowser File->Configure thing. However, this should happen automatically. What I meant was that the actual "Configuration" (BinDiff Path etc.) happens directly in the Plugin GUI.

**Comment by RibShark** [comment]
A binary for 10.1.5 would be appreciated!
