### ISSUE TITLE
Option to import all matches regardless of similarity

### ISSUE THREAD

**Issue by RibShark** [ubfx/BinDiffHelper#15]
I am comparing two binaries, one with symbols and one without, and they share a significant amount of functions. I would like to import all matched function names, but by default BinDiffHelper only selects those with 100% similarity. I would like to import them all, but there seems to be no way to batch select every single one, and going through and selecting thousands of functions manually is not feasible. Please add a way to either batch tick the import box on selected items, or import all matches at once.

**Comment by ubfx** [comment]
Good point, I'll try to add this in the coming days

**Comment by ubfx** [comment]
Took a little longer, but here we are: https://github.com/ubfx/BinDiffHelper/releases/tag/v0.4.2
