### ISSUE TITLE
Unable to import binary for diffing

### ISSUE THREAD

**Issue by vladionescu** [ubfx/BinDiffHelper#18]
Ghidra 10.2.2 on macOS, BinDiff 7, built BinDiffHelper 7f5222974323b9133a2505d9e3547c10aa21ebb2 using Gradle 7.6

BinDiffHelper is pointed at `/Applications/BinDiff/BinDiff.app/Contents/MacOS/bin/bindiff`

When doing "Open file for comparison" from the BinDiffHelper window, it is stuck at 0% exporting perpetually, and cancelling (by trying to close the exporting window) doesn't work, I have to quit Ghidra entirely to stop it and regain control. No console messages. I've tried this with multiple binaries. Any tips?

![Screenshot 2023-01-12 at 2 40 17 PM](https://user-images.githubusercontent.com/5445781/212197295-746c62e4-fe6f-4ae8-9969-47e550c4d58b.png)

**Comment by alandtse** [comment]
Also have same behavior with Ghidra 10.2.3 on Windows 10 with same release so it's not just OS specific.

**Comment by ubfx** [comment]
This should be fixed now: https://github.com/ubfx/BinDiffHelper/releases/tag/v0.4.2
