### ISSUE TITLE
Add a CI workflow using GitHub Actions

### ISSUE THREAD

**Issue by SmileyAG** [ubfx/BinDiffHelper#21]
It would be great to have automatic builds.

And the point is not at all that manual building can be difficult, it’s just that re-building locally for each new version does not seem like a convenient solution.

Here is an example of CI workflow from other Ghidra extension project for reference: https://github.com/chaoticgd/ghidra-emotionengine-reloaded/blob/main/.github/workflows/publish.yml

When there is a CI workflow, it is not difficult to change the following parameters for shipping builds, such as:
- JDK version and distribution
- Gradle version
- Ghidra version

**Comment by antoniovazquezblanco** [comment]
Mostly completed now :D

**Comment by ubfx** [comment]
Thank you @antoniovazquezblanco for tackling this. I made some additional changes by including BinExport in the build as a submodule which removes all of the protobuf hassle from our own gradle build.

**Comment by SmileyAG** [comment]
Great job, guys! I also made pull request with some minor changes to CI, so it is now more flexible for building specific versions of Ghidra.
