### ISSUE TITLE
Support BinDiff 8

### ISSUE THREAD

**Issue by DavidBuchanan314** [ubfx/BinDiffHelper#22]
I hexedited my bindiff 8's version number to pretend to be 7 and it seems to be working fine, so hopefully an easy update :)

**Comment by ubfx** [comment]
Thanks for pointing this out, it was indeed an easy update.

https://github.com/ubfx/BinDiffHelper/releases/tag/v0.5

**Comment by DavidBuchanan314** [comment]
tyvm!
