### ISSUE TITLE
cannot add to ghidra

### ISSUE THREAD

**Issue by jackulder** [ubfx/BinDiffHelper#7]
I've followed instructions to add BinDiff ghidra plugin.
As you mentioned in "How to install" section, I downloaded `BinDiffHelper v0.3.1` and `ghidra_9.1.2_PUBLIC_20200212.zip`.
Then I opened File -> Install Extensions in the main window, and selected BinDiffHelper zip file. ghidra noticed me to restart the program. I did it as well.
I also checked BinDiffHelper in code explorer (file -> configure), but when I started to compare two binaries in ghidra project, in windows -> BinDiffHelper I saw this message:
`the BinExport plugin couldnt be found so some features are disabled.
see the readme at https://github.com/ubfx/BinDiffHelper for a link to the BinExport as binaries or in source.
BinDiff6 binary has not been set so some features are disabled.
go to settings button and select the BinDiff6 binary if you want to connect with BinDiff6 directly
you can download BinDiff 6 from https://zynamics.com/software.html`
How can I solve this error?

**Comment by ubfx** [comment]
There are two different extensions for two different things: **BinExport** and **BinDiffHelper**.

BinExport is provided by google (https://github.com/google/binexport/releases/tag/v11) and if you want to use all features of BinDiffHelper you need to install it, too.

**Comment by jackulder** [comment]
Thanks.
I've downloaded `ghidra_BinExport.zip` via the link you mentioned it. then I added it to ghidra extensions.
When I open windows -> BinDiffHelper, it showed me this message:
`BinDiff6 binary has not been set so some features are disabled. go to settings button and select the BinDiff6 binary if you want to connect with BinDiff6 directly .
You can download BinDiff 6 from https://zynamics.com/software.html`
I checked zynamics.com and downloaded Bindiff6.msi. I installed it so it copied `bindiff6.dll`, `bindiff664.dll`, `binexport11.dll` and `binexport1164.dll` at `C:\Program Files\IDA\Plugins`
I came back to BinDiffHelper window, selected settings and bindiff64.dll.
but an error was raised:
`java.io.IOException: couldn't run this file. Doesn't seem to be the correct BinDiff 6 binary.`
Now, is there another way to select bindiff6?

**Comment by ubfx** [comment]
If you're on windows, you should select "bindiff.exe". In my case, for example, it's located at 
"C:\Program Files\BinDiff\bin\bindiff.exe"

**Comment by jackulder** [comment]
It works!
thanks.
