### ISSUE TITLE
Unable to install the extension on Linux 

### ISSUE THREAD

**Issue by max-r-b** [ubfx/BinDiffHelper#9]
I have been trying to install the Extension on my Ghidra installation on Linux. I am using Ghidra 9.1.2. BinExport is installed and working in Ghidra.

Following the instructions from the Readme, I installed the extension zip file and then restart Ghidra. Then I go into file -> Configure -> configure all button. The problem is that I don't see the BinHelper plugin in the list. Looking at the logs, there is no particular error message...

[logs.txt](https://github.com/ubfx/BinDiffHelper/files/5701445/logs.txt)

I had the exact same issue when building the extension myself. Any idea what the problem can be?

**Comment by max-r-b** [comment]
After an ultimate try, it seems to work. I simply opened one of my project and Ghidra asked me if I wanted to unable a new extension plugin.

**Comment by ubfx** [comment]
Thanks for the feedback, there do seem to be some difficulties on linux and I'll have to test this further
